deckName = "Big";
learning = "eo";
knowing = "ru";
cards = [

 {"lrn":"unu",
 "knw": "один",
 "lrn_ex": ["Mi havas unu pomon"],
 "knw_ex": ["У меня есть одно яблоко"],
 "img":""},
 {"lrn":"du",
 "knw": "two",
 "lrn_ex": ["Mi havas du pomojn"],
 "knw_ex": ["У меня есть два яблока"],
 "img":""},
 {"lrn":"tri",
 "knw": "three",
 "lrn_ex": ["Mi havas tri pomojn"],
 "knw_ex": ["У меня есть три яблока"],
 "img":""},
 {"lrn":"kvar",
 "knw": "four",
 "lrn_ex": ["Mi havas kvar pomojn"],
 "knw_ex": ["У меня есть четыре яблока"],
 "img":""},
 {"lrn":"kvin",
 "knw": "five",
 "lrn_ex": ["Mi havas kvin pomojn"],
 "knw_ex": ["У меня есть пять яблок"],
 "img":""},
 {"lrn":"ses",
 "knw": "six",
 "lrn_ex": ["Mi havas ses pomojn"],
 "knw_ex": ["У меня есть шесть яблок"],
 "img":""},
 {"lrn":"sep",
 "knw": "seven",
 "lrn_ex": ["Mi havas sep pomojn"],
 "knw_ex": ["У меня есть семь яблока"],
 "img":""},
 {"lrn":"ok",
 "knw": "eight",
 "lrn_ex": ["Mi havas ok pomojn"],
 "knw_ex": ["У меня есть восемь яблок"],
 "img":""},
 {"lrn":"naux",
 "knw": "nine",
 "lrn_ex": ["Mi havas naux pomojn"],
 "knw_ex": ["У меня есть десять яблок"],
 "img":""},
 {"lrn":"dek",
 "knw": "ten",
 "lrn_ex": ["Mi havas dek pomojn"],
 "knw_ex": ["У меня есть десять яблок"],
 "img":""},
]



