deckName = "Big";
learning = "eo";
knowing = "ru";
cards = [

 {"lrn":"unu",
 "knw": "один",
 "lrn_ex": ["Mi havas unu pomon"],
 "knw_ex": ["У меня есть одно яблоко"],
 "img":""},
 {"lrn":"du",
 "knw": "два",
 "lrn_ex": ["Mi havas du pomojn"],
 "knw_ex": ["У меня есть два яблока"],
 "img":""},
 {"lrn":"tri",
 "knw": "три",
 "lrn_ex": ["Mi havas tri pomojn"],
 "knw_ex": ["У меня есть три яблока"],
 "img":""},
 {"lrn":"kvar",
 "knw": "четыре",
 "lrn_ex": ["Mi havas kvar pomojn"],
 "knw_ex": ["У меня есть четыре яблока"],
 "img":""},
 {"lrn":"kvin",
 "knw": "пять",
 "lrn_ex": ["Mi havas kvin pomojn"],
 "knw_ex": ["У меня есть пять яблок"],
 "img":""},
 {"lrn":"ses",
 "knw": "шесть",
 "lrn_ex": ["Mi havas ses pomojn"],
 "knw_ex": ["У меня есть шесть яблок"],
 "img":""},
 {"lrn":"sep",
 "knw": "семь",
 "lrn_ex": ["Mi havas sep pomojn"],
 "knw_ex": ["У меня есть семь яблока"],
 "img":""},
 {"lrn":"ok",
 "knw": "восемь",
 "lrn_ex": ["Mi havas ok pomojn"],
 "knw_ex": ["У меня есть восемь яблок"],
 "img":""},
 {"lrn":"naux",
 "knw": "девять",
 "lrn_ex": ["Mi havas naux pomojn"],
 "knw_ex": ["У меня есть десять яблок"],
 "img":""},
 {"lrn":"dek",
 "knw": "десять",
 "lrn_ex": ["Mi havas dek pomojn"],
 "knw_ex": ["У меня есть десять яблок"],
 "img":""},
 {"lrn":"viro",
 "knw": "мужчина",
 "lrn_ex": ["Mi estas viro"],
 "knw_ex": ["Я мужчина"],
 "img":""},
 {"lrn":"virino",
 "knw": "женщина",
 "lrn_ex": ["Mi estas virino"],
 "knw_ex": ["Я женщина"],
 "img":""},
 {"lrn":"gepatroj",
 "knw": "родители",
 "lrn_ex": ["Miaj gepatroj estas Igor kaj Irina"],
 "knw_ex": ["Мои родители это Игорь и Ирина"],
 "img":""},
 {"lrn":"labori",
 "knw": "работать",
 "lrn_ex": ["La viro ne laboras"],
 "knw_ex": ["Этот мужчина не работает"],
 "img":""},
 {"lrn":"dormi",
 "knw": "спать",
 "lrn_ex": ["La viro dormas"],
 "knw_ex": ["Этот мужчина спит"],
 "img":""},
 {"lrn":"dormi",
 "knw": "спать",
 "lrn_ex": ["La viro dormas"],
 "knw_ex": ["Этот мужчина спит"],
 "img":""},
 {"lrn":"manĝi",
 "knw": "кушать",
 "lrn_ex": ["Petro kaj Sofia ne manĝas multe"],
 "knw_ex": ["Петр и София едят много"],
 "img":""},
 {"lrn":"trinki",
 "knw": "пить",
 "lrn_ex": ["Petro kaj Sofia ne trinkas multe"],
 "knw_ex": ["Петр и София не пьют много"],
 "img":""},
 {"lrn":"kun",
 "knw": "c",
 "lrn_ex": ["Mi laboras kun Petro"],
 "knw_ex": ["Я работаю с Петром"],
 "img":""},
 {"lrn":"ne",
 "knw": "нет/не",
 "lrn_ex": ["Ne","Ne scias tion"],
 "knw_ex": ["Нет","Не знаю этого"],
 "img":""},
 {"lrn":"araneo",
 "knw": "паук",
 "lrn_ex": ["Mi ne timas araneojn"],
 "knw_ex": ["Я не боюсь пауков"],
 "img":""},
 {"lrn":"porkaĵon",
 "knw": "свинина",
 "lrn_ex": ["Mi ŝatas porkaĵon"],
 "knw_ex": ["Я люблю свинину"],
 "img":""},
 {"lrn":"danĝera",
 "knw": "опасен",
 "lrn_ex": ["La katoj ne estas danĝeraj"],
 "knw_ex": ["Коты не опасны"],
 "img":""},
 {"lrn":"flugi",
 "knw": "летать",
 "lrn_ex": ["Musxoj flugas"],
 "knw_ex": ["Мухи летают"],
 "img":""},
 {"lrn":"Vosto",
 "knw": "Хвост",
 "lrn_ex": ["Ĝia vosto estas belega","Ĝia vosto estas bela"],
 "knw_ex": ["Его хвост прекрасен","Его хвост красивый"],
 "img":""},
 {"lrn":"strigo",
 "knw": "сова",
 "lrn_ex": ["Strigo estas nokta birdo"],
 "knw_ex": ["Сова - ночная птица"],
 "img":""},
 {"lrn":"libro",
 "knw": "книга",
 "lrn_ex": ["Tio estas lia libro","Tio estas sxia libro"],
 "knw_ex": ["Это его книга", "Это её книга"],
 "img":""},
 {"lrn":"vidi",
 "knw": "видеть",
 "lrn_ex": ["Cxu vi vidas la dangxerajn bestojn?"],
 "knw_ex": ["Вы видите опасных животных?"],
 "img":""},
 {"lrn":"cxevalo",
 "knw": "лошадь",
 "lrn_ex": ["La belaj cxevaloj havas grandajn vostojn"],
 "knw_ex": ["У красивых коней длинные хвосты"],
 "img":""},
 {"lrn":"muso",
 "knw": "мышь",
 "lrn_ex": ["La muso kaj la kato estas malamikojn"],
 "knw_ex": ["Мышь и кот враги"],
 "img":""},
 {"lrn":"kuniklo",
 "knw": "заяц",
 "lrn_ex": ["La kuniklo kaj la vulpo estas malamikojn"],
 "knw_ex": ["Заяц и лиса враги"],
 "img":""},
 {"lrn":"vulpo",
 "knw": "лис",
 "lrn_ex": ["La vulpo and la cxashundo"],
 "knw_ex": ["Лис и охотничий пес"],
 "img":""},
 {"lrn":"viando",
 "knw": "мясо",
 "lrn_ex": ["Mi sxatas bovina viando"],
 "knw_ex": ["Я люблю коровье мясо"],
 "img":""},
 {"lrn":"fisxo",
 "knw": "рыба",
 "lrn_ex": ["Mi sxatas fisxon"],
 "knw_ex": ["Я люблю рыбу"],
 "img":""},
 {"lrn":"lauxta",
 "knw": "громкий",
 "lrn_ex": ["Tri lauxtaj knabinoj logxas en nia domo"],
 "knw_ex": ["Три громких девочки живут в нашем доме"],
 "img":""},
 {"lrn":"nokte",
 "knw": "ночью",
 "lrn_ex": ["Mi ludas nokte"],
 "knw_ex": ["Я играю ночью"],
 "img":""},
 {"lrn":"Ilia",
 "knw": "Theirs",
 "lrn_ex": ["Kiu domo estas ilia?"],
 "knw_ex": ["Который дом их?"],
 "img":""},
 {"lrn":"kapti",
 "knw": "ловить",
 "lrn_ex": ["La hundo kaptas muson?"],
 "knw_ex": ["Собака ловит мышь"],
 "img":""},

]



