deckName = "Big";
cards = [

 {"lrn":"unu",
 "knw": "one",
 "lrn_ex": ["Mi havas unu pomon"],
 "knw_ex": ["I have one apple"],
 "img":""},
 {"lrn":"du",
 "knw": "two",
 "lrn_ex": ["Mi havas du pomojn"],
 "knw_ex": ["I have two apples"],
 "img":""},
 {"lrn":"tri",
 "knw": "three",
 "lrn_ex": ["Mi havas tri pomojn"],
 "knw_ex": ["I have three apples"],
 "img":""},
 {"lrn":"kvar",
 "knw": "four",
 "lrn_ex": ["Mi havas kvar pomojn"],
 "knw_ex": ["I have four apples"],
 "img":""},
 {"lrn":"kvin",
 "knw": "five",
 "lrn_ex": ["Mi havas kvin pomojn"],
 "knw_ex": ["I have five apples"],
 "img":""},
 {"lrn":"ses",
 "knw": "six",
 "lrn_ex": ["Mi havas ses pomojn"],
 "knw_ex": ["I have six apples"],
 "img":""},
 {"lrn":"sep",
 "knw": "seven",
 "lrn_ex": ["Mi havas sep pomojn"],
 "knw_ex": ["I have seven apples"],
 "img":""},
 {"lrn":"ok",
 "knw": "eight",
 "lrn_ex": ["Mi havas ok pomojn"],
 "knw_ex": ["I have eight apples"],
 "img":""},
 {"lrn":"naux",
 "knw": "nine",
 "lrn_ex": ["Mi havas naux pomojn"],
 "knw_ex": ["I have nine apples"],
 "img":""},
 {"lrn":"dek",
 "knw": "ten",
 "lrn_ex": ["Mi havas dek pomojn"],
 "knw_ex": ["I have ten apples"],
 "img":""},
]



